sonar.verbose=true

sonar.projectKey=tweet-trend
sonar.projectName=tweet-trend

sonar.sourceEncoding=UTF-8

# Analyze only Java source
sonar.sources=src/main

# Compiled classes
sonar.java.binaries=target/classes

# JaCoCo report
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclude generated folders
sonar.exclusions=target/**,jarstaging/**,ttrend/**